TELEGRAM_BOT_TOKEN = "8537299524:AAE3Q723lH0ksSSRXhbBTkopPa3hVGbZRek"

PAIR = "XAUUSD"

OANDA_API_KEY = "ISI_JIKA_PUNYA"
OANDA_ACCOUNT_ID = "ISI_JIKA_PUNYA"

FOREX_COM_API_KEY = "ISI_JIKA_PUNYA"

# default settings
TIMEFRAMES = ["M1", "M3", "M5"]
